name: robot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  google_maps_flutter: any
  location: ^7.0.1
  firebase_database: ^11.3.0
  firebase_core: ^3.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/car1.png
    - assets/car2.png
    - assets/car3.png
    - assets/car4.png
    - assets/car5.png
    - assets/burger.png
    - assets/coupon.png
    - assets/grandmother.png
    - assets/siren.png
    - assets/phone.png
    - assets/bell.png